version: "4.25"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    command:
      - --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"  
  tensorflow:
    container_name: ${TENSORFLOW_CONTAINER_NAME}
    build:
      context: ${TENSORFLOW_MODEL_PATH}
      dockerfile: ${TENSORFLOW_DOCKERFILE_NAME}
    ports:
      - "${TENSORFLOW_PORT}:${TENSORFLOW_PORT}"

  app:
    container_name: ${API_NAME}
    build: ./
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./.reports:/app/reports
    env_file:
    - .env

    depends_on:
      - postgres
      - redis
      - tensorflow